### ISSUE TITLE
main.py

### ISSUE THREAD

**Issue by molhck** [fantasydatapros/nba-betting-challenge#3]
Hi,

When I tried to run the main.py file, I have a KeyError with my api that I generate from Odds Api. Do I have to put my API elsewhere than the config.py in the odds_api section?

**Comment by fantasydatapros** [comment]
In order to pull lines from the odds API, you'll need to get an API key from them first: https://the-odds-api.com.

You will then need to set the API key ODDS_API_KEY either via the command line or by creating a .env file.
